"""
Probabilistic Finite State Automata (PFSA) for ZCoR-IPF.

Implements the PFSA inference and Sequence Likelihood Defect (SLD) computation
described in the paper (Methods, Step 2).

A PFSA is a specialized HMM that models categorical stochastic processes.
It's a directed graph with probability-weighted edges that generates sequences
of symbols from a finite alphabet.

For ZCoR-IPF:
- Alphabet: {0, 1, 2} (trinary encoding)
- Each PFSA models the sequential patterns in one disease category's time series
- 204 PFSAs total: 51 categories × 2 cohorts (positive/control) × 2 sexes

The SLD (Sequence Likelihood Defect) Δ measures how much more likely a patient's
sequence was generated by the positive model vs the control model:
  Δ = L(G_0, x) - L(G_+, x) ≈ D_KL(G_0 || G_+)

Reference: Chattopadhyay & Lipson (2013), "Abductive learning of quantized
stochastic processes with probabilistic finite automata"
"""

import numpy as np
from collections import defaultdict, Counter
import warnings


class PFSA:
    """
    Probabilistic Finite State Automaton for trinary sequences.

    Uses variable-order Markov chain estimation as a practical approximation
    to the full PFSA inference described in Chattopadhyay & Lipson (2013).

    The model learns transition probabilities P(next_symbol | context),
    where context is a suffix of the observed sequence up to `max_depth`.
    """

    ALPHABET_SIZE = 3  # {0, 1, 2}

    def __init__(self, max_depth=3, smoothing=1e-6):
        """
        Args:
            max_depth: Maximum context length (Markov order).
                Paper uses PFSA which adaptively determines depth;
                we approximate with fixed max_depth.
            smoothing: Laplace smoothing parameter to avoid log(0).
        """
        self.max_depth = max_depth
        self.smoothing = smoothing
        self.transition_counts = {}  # context_tuple -> Counter of next symbols
        self.transition_probs = {}   # context_tuple -> np.array of probabilities
        self.is_fitted = False

    def fit(self, sequences):
        """
        Learn transition probabilities from a collection of sequences.

        Args:
            sequences: array of shape (n_sequences, seq_length) with values in {0,1,2}
        """
        self.transition_counts = defaultdict(Counter)

        for seq in sequences:
            for depth in range(self.max_depth + 1):
                for i in range(depth, len(seq)):
                    context = tuple(seq[max(0, i - depth):i])
                    symbol = int(seq[i])
                    self.transition_counts[context][symbol] += 1

        # Convert counts to probabilities with smoothing
        self.transition_probs = {}
        for context, counts in self.transition_counts.items():
            total = sum(counts.values()) + self.ALPHABET_SIZE * self.smoothing
            probs = np.array([
                (counts.get(s, 0) + self.smoothing) / total
                for s in range(self.ALPHABET_SIZE)
            ])
            self.transition_probs[context] = probs

        self.is_fitted = True

    def log_likelihood(self, sequence):
        """
        Compute the log-likelihood of a sequence under this model.

        L(x, G) = -(1/|x|) * sum_i log P(x_i | context_i)

        Returns the negative normalized log-likelihood (lower = more likely).
        """
        if not self.is_fitted:
            raise RuntimeError("Model not fitted yet")

        log_prob = 0.0
        n = len(sequence)

        for i in range(n):
            # Try longest context first, fall back to shorter
            prob = None
            for depth in range(min(self.max_depth, i), -1, -1):
                context = tuple(sequence[max(0, i - depth):i])
                if context in self.transition_probs:
                    prob = self.transition_probs[context][int(sequence[i])]
                    break

            if prob is None or prob <= 0:
                prob = 1.0 / self.ALPHABET_SIZE  # uniform fallback

            log_prob += np.log(prob)

        # Return negative normalized log-likelihood
        return -log_prob / max(n, 1)

    def get_n_parameters(self):
        """Number of model parameters."""
        return len(self.transition_probs) * self.ALPHABET_SIZE


class PFSAEnsemble:
    """
    Collection of 204 PFSA models: 51 categories × 2 cohorts × 2 sexes.
    """

    def __init__(self, n_categories=51, max_depth=3, smoothing=1e-6):
        self.n_categories = n_categories
        self.max_depth = max_depth
        self.smoothing = smoothing

        # models[sex][cohort][category] = PFSA
        # sex: 'M' or 'F'
        # cohort: 'positive' or 'control'
        self.models = {
            sex: {
                cohort: [
                    PFSA(max_depth=max_depth, smoothing=smoothing)
                    for _ in range(n_categories)
                ]
                for cohort in ["positive", "control"]
            }
            for sex in ["M", "F"]
        }

    def fit(self, series_array, metadata):
        """
        Train all 204 PFSA models.

        Args:
            series_array: shape (n_patients, n_categories, n_weeks), values in {0,1,2}
            metadata: list of dicts with 'sex' and 'label' keys
        """
        # Split by sex and cohort
        indices = {"M": {"positive": [], "control": []},
                   "F": {"positive": [], "control": []}}

        for i, meta in enumerate(metadata):
            sex = meta["sex"]
            cohort = "positive" if meta["label"] == 1 else "control"
            indices[sex][cohort].append(i)

        total_models = 0
        for sex in ["M", "F"]:
            for cohort in ["positive", "control"]:
                idx = indices[sex][cohort]
                n = len(idx)
                print(f"  Training {sex}/{cohort}: {n} patients, "
                      f"{self.n_categories} categories...")

                if n == 0:
                    warnings.warn(f"No patients for {sex}/{cohort}")
                    continue

                for cat in range(self.n_categories):
                    # Extract all sequences for this category
                    cat_sequences = series_array[idx, cat, :]  # shape (n, n_weeks)
                    self.models[sex][cohort][cat].fit(cat_sequences)
                    total_models += 1

        print(f"  Trained {total_models} PFSA models")

    def compute_sld(self, series_array, metadata):
        """
        Compute the Sequence Likelihood Defect (SLD) for each patient.

        SLD Δ^j = L(G_0^j, x) - L(G_+^j, x) - D_KL(G_0^j || G_+^j)

        For each disease category j:
          - L(G_0, x): log-likelihood under control model
          - L(G_+, x): log-likelihood under positive model
          - Δ = L(G_0, x) - L(G_+, x)

        Higher Δ → sequence more consistent with positive (IPF) model.

        Returns:
            sld_array: shape (n_patients, n_categories) — the SLD per category
            neg_llk: shape (n_patients, n_categories) — negative log-likelihood under control
            pos_llk: shape (n_patients, n_categories) — negative log-likelihood under positive
        """
        n_patients = len(metadata)
        sld_array = np.zeros((n_patients, self.n_categories))
        neg_llk = np.zeros((n_patients, self.n_categories))
        pos_llk = np.zeros((n_patients, self.n_categories))

        for i in range(n_patients):
            if (i + 1) % 5000 == 0:
                print(f"    Computing SLD for patient {i+1}/{n_patients}...")

            sex = metadata[i]["sex"]
            for cat in range(self.n_categories):
                seq = series_array[i, cat, :]

                # Log-likelihood under control model
                ctrl_llk = self.models[sex]["control"][cat].log_likelihood(seq)
                # Log-likelihood under positive model
                pos_l = self.models[sex]["positive"][cat].log_likelihood(seq)

                neg_llk[i, cat] = ctrl_llk
                pos_llk[i, cat] = pos_l

                # SLD: positive values indicate sequence is more IPF-like
                sld_array[i, cat] = ctrl_llk - pos_l

        return sld_array, neg_llk, pos_llk


def compute_pfsa_features(series_array, metadata, max_depth=3, smoothing=1e-6):
    """
    End-to-end: train PFSAs and compute SLD features.

    Returns:
        ensemble: trained PFSAEnsemble
        sld: shape (n_patients, 51) — SLD scores
        neg_llk: shape (n_patients, 51) — control log-likelihoods
        pos_llk: shape (n_patients, 51) — positive log-likelihoods
    """
    print("Training PFSA models...")
    ensemble = PFSAEnsemble(
        n_categories=series_array.shape[1],
        max_depth=max_depth,
        smoothing=smoothing,
    )
    ensemble.fit(series_array, metadata)

    print("Computing SLD features...")
    sld, neg_llk, pos_llk = ensemble.compute_sld(series_array, metadata)

    return ensemble, sld, neg_llk, pos_llk


if __name__ == "__main__":
    import os, csv

    # Load encoded data
    encoded_dir = os.path.join("data", "processed", "encoded")
    print("Loading encoded data...")
    data = np.load(os.path.join(encoded_dir, "trinary_series.npz"))
    series = data["series"]

    with open(os.path.join(encoded_dir, "patient_metadata.csv")) as f:
        metadata = list(csv.DictReader(f))
        for m in metadata:
            m["label"] = int(m["label"])

    print(f"  Series shape: {series.shape}")
    n_pos = sum(1 for m in metadata if m["label"] == 1)
    print(f"  Positive: {n_pos}, Control: {len(metadata) - n_pos}")

    # Train and compute
    ensemble, sld, neg_llk, pos_llk = compute_pfsa_features(series, metadata)

    # Save
    output_dir = os.path.join("data", "processed", "features")
    os.makedirs(output_dir, exist_ok=True)
    np.savez_compressed(
        os.path.join(output_dir, "pfsa_features.npz"),
        sld=sld, neg_llk=neg_llk, pos_llk=pos_llk,
    )
    print(f"\nSaved PFSA features to {output_dir}/pfsa_features.npz")

    # Summary
    print(f"\nSLD statistics:")
    print(f"  Mean:   {np.mean(sld):.4f}")
    print(f"  Std:    {np.std(sld):.4f}")
    print(f"  Range:  [{np.min(sld):.4f}, {np.max(sld):.4f}]")

    # Check separation between positive and control
    pos_mask = np.array([m["label"] == 1 for m in metadata])
    ctrl_mask = ~pos_mask
    print(f"\n  Mean SLD (positive): {np.mean(sld[pos_mask]):.4f}")
    print(f"  Mean SLD (control):  {np.mean(sld[ctrl_mask]):.4f}")
    print(f"  Mean SLD difference: {np.mean(sld[pos_mask]) - np.mean(sld[ctrl_mask]):.4f}")
